### PR TITLE
Issue1 markdownlint

### LINKED ISSUE #1: markdownlint throwing some warnings
Need to cleanup outstanding warnings.  

Running with the following config:

```json
{
    "MD033": false,
    "MD013": false
}
```

### PR DESCRIPTION
**Pull request by chicks-net**
Fixes #1 

.... as much as makes sense at this point.

### CODE REVIEW

**Comment by chicks-net** [comment]
> Can you kindly squash

I thought that happened when it got merged.  Do we not like the "Squash & Merge" button?

**Comment by markyjackson-taulia** [comment]
Squash merging is an option but then that means the merger has to decide the final squash messages.
I prefer the person whom opened the pr to actual squash the commit and select the commit message

**Comment by sbtaylor15** [comment]
I am squashing and merging this so I can do a new PR another branch and minimize the files being merged

**Comment by chicks-net** [comment]
Thanks @sbtaylor15 .  I'll pre-squash for my next PR.

**Pull request merged**
